### PR TITLE
Changes to improve node dockerfile and to resolve https://github.com/msa...

### PR DESCRIPTION
**Pull request by longieirl**

### CODE REVIEW

**Comment by longieirl** [comment]
What os are you using? Im on a mac running 'Boot2Docker-cli version: v1.3.0'.

**Comment by msanand** [comment]
I'm also on Mac, running Boot2Docker-cli version: v1.5.0

**Comment by longieirl** [comment]
My understanding is that mounting the volumes will wipe the /src directory which had the node_modules downloaded inside the container. If you have the node_nodules already inside your node folder then you wont see any errors as they will be copied over when the volume is loaded. I've pushed another change that will cache the node_modules [http://bitjudo.com/blog/2014/03/13/building-efficient-dockerfiles-node-dot-js/].

**Comment by msanand** [comment]
You're right @longieirl  ! The volume mounting was the culprit. I was able to reproduce the issue by deleting my local node_modules. The caching option is an interesting change as well. The commit looks good to be merged!
But I still have one gap in the workflow. The intention of mounting the local dev directly in the container was to keep the development changes in sync with the container content - to make it easier to quickly see local changes running on the container without having to re-build the container. In such a dev environment, there would be a local node_modules folder (like in my case), so this issue wouldn't occur. 
So, how to achieve this quick dev turnaround without losing the node_modules folder is still an open point.

**Pull request merged**
